### ISSUE TITLE
Option to specify UNAuthorizationOptions for Beacon notifications

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#106]
My app registers with UNUserNotificationCenter with `provisional` UNAuthorizationOptions, which allows it to avoid explicit notification permissions alert. 

After integrating Beacon notifications support, my app is showing explicit permissions alert, right after the first conversation has been ended. My guess is because the set of authorizations options that the SDK requests are different (superset) of mine, already granted provisional permissions.

I need a way to control or at least influence this behavior. Possibly giving me an option to check with the user if they're ready to make this decision and explain why the app is asking for permissions now.

**Comment by ScottPetit** [comment]
👋 @andreyz,

Yea the behavior you're describing is the currently expected behavior.  If `HSBeacon` is initialized with push notification support then Beacon will request authorization when a user sends their first message through the contact form, or when they start a chat.  This is so that when you reply to a conversation, or as you interact in a chat and the user doesn't have chat foregrounded we can notify your users about those interactions.  For extra context we're requesting `[.sound, .alert, .badge]`.

Just so I'm clear, it seems like you're asking for a couple of things here:

1. To be able to control which options notification options Beacon requests authorization with?
2. To have a callback prior to Beacons requests for that authorization to be able to show some UI to your user about the incoming alert?

**Comment by adrianne-helpscout** [comment]
Closing this issue as the developer never responded with more info. Although this author did chime in on #148; so, we are tracking their interest on [that internal issue](https://helpscout.atlassian.net/browse/IOSSDK-471)

**Comment by andreyz** [comment]
Wow. It took over a year and still no progress on the issue.
