### ISSUE TITLE
Beacon screen is too small on iPad

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#107]
Hello,

When opening Beacon on iPad, I notice that it's not fullscreen and looks too small. Is it a point need to be marked as enhancement?

Beacon SDK: 2.0.1

Thanks,
Binh

**Comment by ScottPetit** [comment]
Hey 👋  @BinhTNT,

Just want to verify that this is the behavior you're seeing. 
![IMG_64887C94B340-1](https://user-images.githubusercontent.com/2100009/92646117-8d2baa80-f2ab-11ea-9c2c-720f3d4f462b.jpeg)?

If so, that's the expected behavior when presented on a full screen iPad app.  Beacon should dynamically resized itself when presented in split screen on iPad, but when the app is full screen it's presented as an iPad modal would be presented.

**Comment by BinhTNT** [comment]
Hi @ScottPetit Yeah, it's the same as your screenshot in my side. Thank you for your confirmation.
