### ISSUE TITLE
Custom attributes not passed to helpscout by beacon

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#115]
For some reason I am not getting any context form customers after updating to 2.0.2. Anyone else seeing this?

Beacon version: 
2.0.2

Actual: 
No custom attributes are being passed into HelpScout from the beacon. 

Expected:
Beacon should pass custom attributes to the HelpScout sidebar

EDIT: Changed wording to clarify based on feedback by @scottyab below

**Comment by scottyab** [comment]
Hey @sipersso can you just expand on what you mean by context? are you talking about the customer information that is shown in the Help Scout side bar when viewing a conversation created via the Beacon iOS SDK? or something iOS specific? Thanks

**Comment by sipersso** [comment]
Yes, exactly. The custom attributes are missing in the HelpScout sidebar. It is only happening on the iOS beacon. Android seems fine.

**Comment by scottyab** [comment]
Thanks, for the clarification @sipersso. We've been trying but have been unable to recreate with 2.0.2. Before I raise a ticket for further investigate. 

1) Can you confirm below is how you're setting the user attributes? if you could copy/paste here that would be great.
2) You're sending the message via the SDK and before calling `user.clearAttributes()`


```
let user = HSBeaconUser()
user.name = "John Appleseed"
user.email = "john_appleseed@example.com"
user.addAttribute(withKey: "application", value: "Your String Value ")
user.addAttribute(withKey: "foo", value: "bar")

HSBeacon.login(user)
```

<img width="279" alt="Screen Shot 2020-09-24 at 9 22 16 AM" src="https://user-images.githubusercontent.com/404105/94163763-1e8c4680-fe80-11ea-8d57-649c5bc5cbd3.png">

**Comment by sipersso** [comment]
I don't use it exactly like that. I set the beacon user once the user logs in and add user attributes from a thin analytics layer and clear the attributes when signing out. I am not using secure mode (as this hides the email field, which I don't want)

But If you can't reproduce it I am sure there is something in my current usage that is causing errors. But it is strange that it stopped working when the beacon library and I don't have any of these issues on Android. 

But I'll investigate it more on my end.

**Comment by scottyab** [comment]
Thanks for getting back to us. As you say User attributes are working a-ok on Android so that tends to rule out a Server/API issue and we've not been able to reproduce via iOS SDK _yet_ so it does seem to indicate some usage difference. 

I'm not clear on how your usage differs from the above?  I would expect you to be able to use the above snippet after the user logs in. As long as you're calling `HSBeacon.login(user)` before Beacon is being launched? Maybe you're not using `user.name`? 

Maybe it's your Beacon's config or the way your launching the Beacon is different form our attempt to reproduce? 

I appreciate it can be a burden to add steps to reproduce but this might help us narrow it down. Alternatively a quick screen recording and/or snippets of the code would also help.

**Comment by sipersso** [comment]
There might be some time between creating the user, which I do when the user logs into the app and when the attributes are added. 

I do call HSBeacon.login before the beacon is being launched. I don't call user.name. Is that a required field?

I'll investigate this more on my end.

**Comment by scottyab** [comment]
`user.name`, isn't required I was just trying to understand if that was a difference in our implementations 🤔

**Comment by sipersso** [comment]
Hi @scottyab!

Just to let you know. I was able to reproduce this by slightly modifying your example. 

```
let user = HSBeaconUser()
user.name = "John Appleseed"
user.addAttribute(withKey: "application", value: "Your String Value ")
user.addAttribute(withKey: "foo", value: "bar")
HSBeacon.login(user)
```

If you don't pass an email on login. Attributes will not be sent to HelpScout. This error was introduced in the 2.0.0 release and was not an issue in 1.0.5 and it isn't an issue on Android.

I do not want to pass email at login. The simple reason is that I cannot be sure that this is an email the customer can be reached at, especially if they are using Sign In With Apple. 

For me personally, this issue is pretty severe as I am heavily relying on user attributest to be able to deliver good support. Right now I am flying blind.

Thanks for checking it out!

**Comment by scottyab** [comment]
Hey @sipersso Nice work reproducing! I didn't think to attempt without an email as the endpoint we send the user attributes to requires the email address as it's saving the attributes on the Help Scout user and that's keyed off the email. 

The contact form or the chat will request the email as part of the UI if one hasn't been provided via login()/identify() and we should be uploading the user attributes after a successful send. Potentially the logic there has changed since 1.0.5? We'll look into.   

Just to clarify your steps to reproduce before creating the internal ticket. 

1. Provide user attributes as noted in the code sample [here](https://github.com/helpscout/beacon-ios-sdk/issues/115#issuecomment-699634996)
2. Open Beacon  and nav to the contact form
3. Input required contact form data including email addresss
4. Send Message
5. Check Help Scout for message and observe the user properties side bar

Expected:
* Name: John Appleseed` and attributes `application:` and `foo` should be populated. 

Actual: 
* Attributes are not populated. 


Just thinking as a workaround could you use the [Session attributes](https://developer.helpscout.com/beacon-2/ios/#session-attributes)in the meantime? They would appear in the Beacon visitor activity note in the conversation like this. 
![Image 2020-09-28 at 10 37 39 am](https://user-images.githubusercontent.com/404105/94416465-cb174280-0176-11eb-8006-f2ed3bf937a4.png)

**Comment by sipersso** [comment]
@scottyab Thanks. Yes, this was definitely changed in 1.0.5. I did try to downgrade to 1.0.5, and when I did, the custom attributes were populated. Thanks for suggesting the Session Attributes workaround. I wasn't aware of these and I should be able to use this until the issue is fixed.

**Comment by ScottPetit** [comment]
Hey 👋 @sipersso ,

Thanks for bringing this to our attention. I just wanted to let you know that user attributes should now propagated correctly in the latest version (2.1.0). If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by ScottPetit** [comment]
Hi @sipersso, as you know, we discovered an issue with version 2.1.0 where under certain configurations Beacon wouldn't be able to be dismissed. Therefore we decided to remove 2.1.0 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by ScottPetit** [comment]
Hey 👋 @sipersso ,

Thanks for bringing this to our attention. I just wanted to let you know that user attributes should now propagated correctly in the latest version (2.1.1). If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
