### ISSUE TITLE
App crashes when you try to record a video to attach it to beacon contact us form.

### ISSUE THREAD

**Issue by mehedihasan619** [helpscout/beacon-ios-sdk#118]
**Actual outcome**: The app crashes when you try to record a video to attach to beacon contact us form.

**Expected outcome**: Users should be able to record video and attach it to the form

**Reproduction Steps**

1. Open beacon form
2. Tap on the attachment icon
3. Accept permission popups if needed
4. When the camera opens tap on Video

Device/OS: iPhone 11/iOS 14

Crash Reason: TCCAccessRequest

**Comment by ScottPetit** [comment]
Hey 👋 @mehedihasan619,

Beacon seems to be crashing because the app doesn't have the appropriate permissions to access videos in the `Info.plist`.  Can you verify that your `Info.plist` has values for all of the following keys:

- `NSPhotoLibraryUsageDescription` 
- `NSCameraUsageDescription` 
- `NSMicrophoneUsageDescription` 
- `NSPhotoLibraryAddUsageDescription`

There's more info about these keys available in our [docs](https://developer.helpscout.com/beacon-2/ios/#photos).  Let us know if that solves your issue.

**Comment by mehedihasan619** [comment]
Thanks, @ScottPetit.
We will check it and update our findings here.
Have a great weekend.

**Comment by scottyab** [comment]
@mehedihasan619 Sounds like this is a permission issue. Please reopen this issue if @ScottPetit's suggestion doesn't work and we'll dig a bit deeper into this. Thanks
