### ISSUE TITLE
Beacon should ask for push notification permission when user attempt to send a message if it's not enabled

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#122]
Hello,

When the app is installed for the first time and the push notification permission is not enabled, the Beacon should ask user for allowing push notification permission if user begin to send the message to make sure they will receive notification after a replied from support team. As I recall, the SDK version 1.0.5 worked this way. Should it be supported for latest version?

Beacon SDK version: 2.0.2

Thanks,
Binh

**Comment by jotaemepereira** [comment]
👋  Hi @BinhTNT! We currently show the push notification permission dialog after the user sends its first message, for the following messages the message is not shown.

There could be some scenarios where the push notifications dialog is not prompt:
1 - Push notifications are not initialized correctly when setting up Beacon
2 - The host app is using push notifications too and already asked for the user permission
3 - If the dialog was already prompt

Can you provide me with your push notification setup on Beacon? So we can dig further. Thanks!

**Comment by BinhTNT** [comment]
Hi @jotaemepereira The Beacon push notification works well in our app as I also posted other issue related to push notification here: https://github.com/helpscout/beacon-ios-sdk/issues/116

_1 - Push notifications are not initialized correctly when setting up Beacon_
--> It's OK as I mentioned above
_2 - The host app is using push notifications too and already asked for the user permission_
--> Our app manages to show push notification permission dialog when needed, let says via a switch control. I'm sure that I was not asked yet.
_3 - If the dialog was already prompt_
--> As I said at point 2, It will not appear if user don't toggle on it via a switch control

I attached the source code files that we integrated Beacon push notification. Note that our project is using React Native, so please ignore the part of code related to React Native. I hope it would be helpful for your investigation.

Thanks,
Binh
[hs_pn_src.zip](https://github.com/helpscout/beacon-ios-sdk/files/5303181/hs_pn_src.zip)

**Comment by jotaemepereira** [comment]
Thanks for providing the source code, I'm going to take a deep look to see what could be happening. Just one more thing, can you confirm if this is only happening on iOS 14? Are you able to reproduce this issue on iOS 13? Thanks.

**Comment by BinhTNT** [comment]
Hi @jotaemepereira I found the issue on iOS 13.  I haven't tried on iOS 14 yet.

**Comment by jotaemepereira** [comment]
Hey @BinhTNT, unfortunately, I was not able to reproduce the issue you are seeing. I've created an app from scratch, installed the iOS Beacon SDK, and after sending the first message through the contact form, the push notification permission was shown.

Checking the implementation you provided, the push notification setup is okay. Something that I would like to remark is that we do not ask for the permission when the app has already requested for push notifications, because when that happens, the `didRegisterForRemoteNotificationsWithDeviceToken` is called on the `AppDelegate` and `[HSBeacon setDeviceToken:deviceToken];` is called, and internally we check if a `deviceToken` is present before asking for permission; If not, we call the Apple implementation to ask for it.

Is it possible for you to try to make a clean install of your app and see if the permission dialog is shown? Another thing, are you receiving push notifications even when the permission dialog is not shown? Thanks!

**Comment by BinhTNT** [comment]
Hi @jotaemepereira That is fabulous from your remarking!
I could found the problem in my side. There was an Firebase api in React Native side was called indeed that make didRegisterForRemoteNotificationsWithDeviceToken triggered. By removing it, now the permission dialog is shown! 

Thanks a lot for your kindly help!

**Comment by jotaemepereira** [comment]
Hey @BinhTNT, I'm happy you were able to resolve it 😄 , let us know if you have any other issue.
