### ISSUE TITLE
Calling openBeacon will open contact form instead of articles list if user opened contact form previously

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#131]
Hello,

I have encountered an issue with SDK 2.1.1. If I open contact form using [HSBeacon navigate:@"/ask/message/" beaconSettings: settings], then I open Beacon home screen with articles by calling openBeacon method, but it will open contact form instead of Answer screen with articles list. Another issue with Beacon home screen is that it doesn't display Answer/Ask tab bar, sometimes I can see it but not at all.

Xcode version: 12.1
iOS version: 14
Beacon SDK: 2.1.1

**Actual outcome**
    Beacon opens contact form instead of Beacon home screen

**Expected outcome**
    Beacon should open Beacon home screen

**Steps to reproduce**
1. open contact form by a menu, lets say "Contact us" menu
2. close contact form, open Beacon home screen by a menu, lets say "Help Center" menu
3. Notice that it opens contact form instead of Beacon home screen. At this time, the app cannot open Beacon home screen any more.

Could you please help?
Thanks,
Binh

**Comment by sipersso** [comment]
Thanks @BinhTNT! Looks like I am not alone using the beacon in this way. I have been having a separate "Contact us" option and a separate "Help Center". 

This has caused a lot of problems since the beacon remembers state. I had a long discussion about this here https://github.com/helpscout/beacon-ios-sdk/issues/80.

I wrote about the following scenario in #80 and I think this is the same as the one you are reporting? 
1: The user opens the beacon from screen 1 where relevant articles to screen 1 is shown.
2: The user contacts support and the user is navigated to the "We're on it" screen
3: The user opens the beacon from screen 2 where I have configured relevant articles to screen 2.

In this case, the user will not be taken the relevant articles to screen 2, instead the user will be taken to the "We're on it"-screen and will never see the help articles related to the screen the user is on, unless he presses "back", which is super weird.

**Comment by scottyab** [comment]
Hey @BinhTNT @sipersso thanks for the detailed report and comment. I have recreated and can understand this state restore behaviour can cause confusion when using the custom navigation. I've raised and discussing this with the mobile team, we'll keep you posted.

**Comment by scottyab** [comment]
We have an[ custom navigation option](https://developer.helpscout.com/beacon-2/ios/#navigate-to-a-specific-screen) within the iOS SDK to force opening the Beacon to Ask/Answers (we call it home) screen. In your case the "Help Center" menu could instead of  `HSBeacon.open(..)` use : 

* ObjC `HSBeacon.navigate("/")` 
* Swift `HSBeacon.navigate(.home)`

Let us know if this suggestion resolves the issue. 

We still have some work to do as theres a screen transition animation that shouldn't be there. It should just load the desired screen regardless of the previous screen. We have a [internal ticket ](https://helpscout.atlassian.net/browse/IOSSDK-261) to resolve this.

**Comment by codenameDuchess** [comment]
@BinhTNT 👋 Thanks for reporting this issue. We wanted to let you know we fixed this in the latest version (2.2.0). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
