### ISSUE TITLE
Bundle resource included twice

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#149]
- Beacon install method: 
    [ ] Carthage, 
    [ X ] CocoaPods, 
    [ ] Swift Package Manager,
    [ ] Manual
- SDK version: 2.1.2
- iOS OS version: 14.3
- Device make/model: All

I've been digging into my app's size to make optimizations, and I noticed that the Beacon.bundle is showing up _twice_ in my IPA. Once in the embedded Beacon XCFramework, and once in the root level (as expected with CocoaPods copying as part of the resources step). This adds ~20% extra to the size needed to add Beacon to an iOS app.

There's gotta be a way to not duplicate the bundle resources, right? Not sure which of the two locations is the _right_ one, but I can't imagine both are needed.

<img width="692" alt="Screen Shot 2021-01-22 at 10 45 21 AM" src="https://user-images.githubusercontent.com/171163/105512542-3a252380-5c9f-11eb-84ea-eb57c45a8a10.png">
(red items are detected duplicates)

Context: many of my users download the app over mediocre cellular data at ski resorts, so an extra meg adds up.

**Comment by hs-gv** [comment]
Thanks for contacting us @parrots .  While researching this issue, the team found another [example](https://stackoverflow.com/questions/30602808/how-to-prevent-swiftsupport-libraries-to-be-included-twice/33490415#33490415) of duplicate libraries included in the .ipa files.  The duplication of Beacon seems to be something we have no control over unfortunately.  Regarding the size of your app, the linked question points to an [Apple Developer forum thread](https://developer.apple.com/forums/thread/16339?answerId=48105022#48105022) where it is mentioned that the App Store will thin down the app and remove unnecessary content.

**Comment by parrots** [comment]
@hs-gv the app thinning mentioned there does not work with regards to duplicated content. Simply things like Swift libraries not needed (iOS 12.3+), asset catalogs only shipping the correct resolution (2x vs 3x) for the device, or difference architecture slices of the binary (32bit vs arm64, etc). Both of those posts reference the swift dynamic libraries inclusion as the root of the question, which is a very very different story.

**Comment by ScottPetit** [comment]
Hey 👋 @parrots,

I think you're right and if you wouldn't mind running a quick test for me to see about the fix I'd really appreciate it.

So if you could create a file from this [gist](https://gist.github.com/ScottPetit/795eec2e31f3c7106ba3f2adf6d0e7b1) named `Beacon.podspec` and update your Podfile to point to that file which should look something like 

```ruby
pod 'Beacon', :podspec => "./Beacon.podspec" # Or wherever you saved `Beacon.podpsec relative to your Podfile
```

So just to walk through the hopeful fix.  That podspec is based off of the latest [podspec](https://github.com/helpscout/beacon-ios-sdk/blob/master/Beacon.podspec) except with the additional `s.resources` reference removed.  So that should keep the `Beacon.bundle` in the `Beacon.xcframework` and not have CocoaPods copy a resource that isn't needed.

The two things to check would be:
1. That we went from 2 `Beacon.bundle`s to 1 (Obviously)
2. That Beacon continues to render resources correctly (really just that buttons have images, storyboards look like they loaded etc) which should be pretty obvious

Let me know if you're able to try out the local podspec and if it fixes your problem.

**Comment by parrots** [comment]
Thanks @ScottPetit for looking into this. Happy to help.

<img width="879" alt="Screen Shot 2021-01-25 at 1 33 44 PM" src="https://user-images.githubusercontent.com/171163/105750073-3c42e880-5f12-11eb-9508-1b4b947cda03.png">

I'm not seeing the resources bundle as a duplicate anymore with the pod spec, and I don't see any oddly missing resources when using Beacon in-app. Everything works the same as before best I can tell. So I think you're good to go with this.

**Comment by ScottPetit** [comment]
Hey @parrots,

This is now available on `master`.  You can access by updating your Podfile to point at

```ruby
pod 'Beacon', :git => 'https://github.com/helpscout/beacon-ios-sdk.git', :commit => '1fd82f6'
```
or
```ruby
pod 'Beacon', :git => 'https://github.com/helpscout/beacon-ios-sdk.git', :branch => 'master'
```

Once we release a new version you should be able to go back to just `pod 'Beacon'`.

Thanks for reporting it, and helping test the fix.
