### ISSUE TITLE
Beacon does not display an error message if the video file is above 10mb

### ISSUE THREAD

**Issue by mehedihasan619** [helpscout/beacon-ios-sdk#156]
Actual Result: If you choose a video file over 10 MB and immediately minimize the app, Beacon does not display an error message or upload your video file.

Expected Result: Beacon should upload files when the app is in the background or throw an error message (if the file is above 10 MB) when a user opens the app next time.

Steps to reproduce:

1. Open Help Scout Contact Form
2. Enter name, subject, and message
3. Select a video file that is over 10 MB (e.g 15MB) from the upload window
4. Immediately minimize the app
5. Open the app after a few mins (2/3 min)
6. Notice that you see no error message or feedback

If you try steps 1-3 again and wait for the file to be uploaded you will see an error message.

**Comment by aliripe** [comment]
Hey @mehedihasan619,

We check the file size before we even attempt to upload the attachment and, if it exceeds 10MB, we show an error message straight away, no connection is performed.

Since we don't perform any request and show the error message straight away, you won't see any error when the app is in background or you come back to the app, because we already informed the user that "Attachments may not be larger than 10MB".

Do let me know if this clarifies the issue or if you have any other questions.

**Comment by adrianne-helpscout** [comment]
@mehedihasan619 Please feel free to reopen this issue if it requires our further attention.
