### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#17]
* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

Version 0.69
Code triggering Beacon:
```
HSBeaconSettings *settings = [[HSBeaconSettings alloc] initWithBeaconId:@"xxx"];

settings.color = [UIColor primary];

[HSBeacon navigate:@"/ask/message/" beaconSettings:settings];
```

**Actual outcome**
Beacon SDK will randomly crash sometimes. Usually some combination of heading to the message view, backing out and poking around the FAQ, then back in and out of the message view.

**Expected outcome**
Beacon should never crash the app.

**Screenshots or GIFs**
Stack trace: 
<img width="409" alt="screen shot 2018-12-06 at 9 15 39 pm" src="https://user-images.githubusercontent.com/171163/49623575-39848280-f99c-11e8-855d-4431046f47e0.png">

**Comment by jgritman** [comment]
Hi Curtis! Thanks for pointing this out!

There's some code in the SDK to generate a link back to the app in the App Store for the Beacon activity log. We use the snippet from [this StackOverflow answer](https://stackoverflow.com/a/9510132/869) to build that.

Based on your stack trace, it looks like `[[[NSBundle mainBundle] infoDictionary]   objectForKey:@"CFBundleName"]` is returning `nil`. We haven't seen this happen before - do you know anything in your setup that could cause that?

Regardless, we're going to rework the activity logging with more sensible values and pull that code out.  This was one of the first things we wrote for the SDK and it hasn't been looked at since then. We hope to have a release out with that later today.

I'll let you know when that's ready. Sorry for the trouble!

**Comment by parrots** [comment]
Ah, I see. I do not have a CFBundleName entry in my Info.plist (5 years in the App Store without one 🤷‍♂️). CFBundleDisplayName is shown everywhere by the system, and if I'm not mistaken CFBundleName is only used as a fallback if that is empty. But I'll add that entry for now. Thanks!

**Comment by jgritman** [comment]
The code referencing `CFBundleName` was removed in release 0.71. Links in the Beacon note will now go to the viewed article.
