### ISSUE TITLE
Beacon Can not ask for feedback everytime?

### ISSUE THREAD

**Issue by navnitsensussoft** [helpscout/beacon-ios-sdk#170]
![Screenshot 2021-11-12 at 2 52 33 PM](https://user-images.githubusercontent.com/83959227/141443231-996facb9-df52-4e53-9968-ca97582214b1.png)

is there any possibility to ask for feedback every time ?

**Comment by codenameDuchess** [comment]
Hi @navnitsensussoft,

Thanks for taking the time to submit an issue and for providing a screenshot. You can learn more about enabling and disabling [Article Ratings](https://docs.helpscout.com/article/1293-docs-article-ratings) for your Beacon on our website.

If you’re not consistently seeing the rating prompt with Article Ratings enabled, would you please provide us with a few more details so that we may try to reproduce the issue and address your question? For instance are you opening [directly to an article](https://developer.helpscout.com/beacon-2/ios/#opening-to-an-article), and where you see the rating prompt is missing? Video of this issue would be greatly appreciated as well.

> **Please provide the following:**
> 
> - **Please ensure you are testing on the latest version of the SDK ahead of submitting a report.**
> - **All reports are required to include steps to reproduce any issues reported.** 
> - **Issues logged without this information may be closed until more information is made available.**
> 
> **Technical Details:**
> 
> - Beacon install method: 
>     [ ] Carthage, 
>     [ ] CocoaPods, 
>     [ ] Swift Package Manager,
>     [ ] Manual
> - SDK version:
> - iOS OS version:
> - Device make/model:
> - Impacted user count:
> 
> **Actual outcome**
> 
>     Beacon did or did not...
> 
> **Expected outcome**
> 
>     Beacon should...
> 
> **Steps to reproduce**
> 
>     1…
>     2…
>     3…

Once you’ve provided these details we’ll dig in, and see if we can get to the bottom of the behavior you’re encountering. Thanks again for taking the time to report this problem.

**Comment by codenameDuchess** [comment]
Closed until more information is made available.

**Comment by navnitsensussoft** [comment]
Hi @codenameDuchess 

Thanks for your answer and let me attach video to know problem. 

https://drive.google.com/file/d/1O_eU1K1aT7CKy8qEn_VgJYFUHt83Gmzi/view?usp=sharing 

Please check and let me know. 

Thanks

**Comment by codenameDuchess** [comment]
Hi @navnitsensussoft,

Thanks for providing the video. I understand your question a bit better now. It is our policy that [each visitor can only rate a docs article a single time](https://docs.helpscout.com/article/1293-docs-article-ratings#how). So once they rate an article (whether logged in or not) they cannot rate the same article again. 

If you'd like to request the feature of being able to control this behavior with a setting in order to allow multiple ratings please send us an email at help@helpscout.com with a bit more information about your use case. I can't guarantee we'll make a change, but if enough users request the feature perhaps in the future we'll be able to add it. 

Thanks and sorry I did not have better news for you on this request.
