### ISSUE TITLE
Support custom CSS for Beacon

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#27]
We would like to customize the style of the Beacon pages to better match the style of our app Genius Scan. To do this, we would like to be able to configure a custom style sheet on the Beacon view in the app.

**Comment by adrianne-helpscout** [comment]
@bvirlet It was an intentional design decision to not provide custom style sheets for Beacon as there are some accessibility concerns. The customizations that we do provide on web and mobile are available through the Beacon Builder. You can find more custsomization documentation [here](https://developer.helpscout.com/beacon-2/ios/#settings-customization) and[ here ](https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html)
