### ISSUE TITLE
iOS 13 Dark Mode

### ISSUE THREAD

**Issue by kcfancher** [helpscout/beacon-ios-sdk#32]
Are you planning on adding changes for iOS 13 Dark Mode, or is the plan to leave the rendering as black text on a white background?

**Comment by samsymons** [comment]
Hey @kcfancher! Absolutely, Beacon SDK's Dark Mode support is on our roadmap. I don't have a good estimate of a timeline for the changes, but I'll let you know here when we push an update. Thanks for the request!

**Comment by bvirlet** [comment]
Hello! I

Can this be bumped up as a bug: in dark mode, the text field and the highlight for the selection are dark, while the background is light:

![IMG_57428FB2B00F-1](https://user-images.githubusercontent.com/792706/63852888-a3651200-c999-11e9-9bad-92f732cc25ef.jpeg)

**Comment by kcfancher** [comment]
With iOS 13 being imminent I'd also like to request this gets bumped.

A couple of bugs I've noticed

- [ ] The nav bar background color does not reliably change between light/dark modes of a dynamic color set using `HSBeaconSettings.color`.
- [ ] The title color doesn't reliably change. There doesn't seem to be a property to change this, but it sometimes switches between light/dark text - but not always. This makes it difficult to read if a dark text is drawn in dark mode with a dark nav bar color.
- [ ] As noted above the 'What can we help you with?` search field looks really odd compared to the rest of the interface.

A general dark mode overhaul would be greatly appreciated, but the bugs above (esp 1 & 2) are a very high priority for usability.

**Comment by adrianne-helpscout** [comment]
https://helpscout.atlassian.net/browse/IOSSDK-5

**Comment by ScottPetit** [comment]
👋 Hey @kcfancher,

Thanks for filing this ticket.  I just wanted to let you know that the bugged portions of Dark Mode (randomly changing colors, dark text rendering on dark backgrounds) should be fixed with version 1.0.2.

We're not quite ready for a full dark mode revamp (although it's on our roadmap like @samsymons mentioned) but Beacon should now look it's normal light mode self even on devices running dark mode.

**Comment by rafaelks** [comment]
@ScottPetit Do you have any idea when dark mode will be released? It's super annoying to be using the app in dark mode and open a very light screen like the HelpScout one -- maybe some appearance customization would be helpful already. Thanks!

**Comment by ScottPetit** [comment]
Hey @rafaelks,

Unfortunately I don't.  As you may know we generally don't disclose release dates publicly since things have a way of changing.  If I'm being honest you should probably lodge a new issue to this project,  since the reason this was closed was because we improved support for dark mode by explicitly opting out, but not actually adopting it.
