### ISSUE TITLE
Error message: please complete all fields

### ISSUE THREAD

**Issue by thaitanloi365** [helpscout/beacon-ios-sdk#51]
Hello, my name is Loi.
I have been using HelpScout Beacon for support user in app.

I don't know why I always got the message "Please complete all fields" although I'm using "secure mode" and I did fill 2 fields (subject and message) like the image.

If I back and click "Get in touch" again, then I can click "Send a message" without this error.

My app is writing in Flutter, I created this repo https://github.com/thaitanloi365/flutter_help_scout

Please help.

* Beacon install method: [ ] Carthage, [ ] CocoaPods, [ ] Manual
I installed the library via CocoaPods.

**Actual outcome**

**Expected outcome**
It shouldn't show the message if user already logged in.

**Screenshots or GIFs**
![Simulator Screen Shot - iPhone 8 - 2020-01-12 at 16 55 45](https://user-images.githubusercontent.com/16873986/72217131-0d531200-355d-11ea-81ce-547eead5f3aa.png)

Any examples of the issue

**Comment by samsymons** [comment]
@thaitanloi365 Thanks for the report! I've logged this internally and will take a look into it and get back to you!

Internal Jira ticket: https://helpscout.atlassian.net/browse/IOSSDK-108

**Comment by ScottPetit** [comment]
Hey @thaitanloi365 thanks again for the report.  Fortunately it seems like this issue was resolved in v1.0.3 which is the latest version up on Cocoapods.  Would you mind seeing if upgrading to 1.0.3 resolves the issue?

I'm going to go ahead and close this but feel free to open another issue if upgrading 1.0.3 doesn't solve the problem.
