### ISSUE TITLE
Prefill method is not called when expected resulting in missing crucial information from our users

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#55]
Hello,

We are encountering yet another problem, this time with Beacon 1.0.4.

* Beacon install method: [x] Carthage

**Actual outcome**

Sometimes the prefill delegate method is not called. This means that the user information we need to support the user is missing.

**Expected outcome**

The prefill delegate method must be called every time the HSBeacon.open() is called with a settings object that specifies a delegate.

**Reproduce steps**

- Open HSBeacon.open(). Do not go to the Ask tab. Observe that the prefill() delegate method has not been called yet.
- Clear all the attachments and prefilled info
- Close Beacon
- Reopen Beacon and go to the Ask tab
- Observe that the prefilled data is missing. Observe that the prefill() delegate method has not been called.

**Note that if you open HSBeacon.open() and directly go to the Ask tab, the prefill() data will be present and it will be present for subsequent opens**

---
- Under what circumstances is it possible that the `prefill()` method would not be called? The `delegate` is alive when the Beacon is displayed.
- Again, the fact that the SDK is closed source prevents us from quickly investigating this issue, understanding the logic that could cause this and fixing it ourselves.

**Comment by bvirlet** [comment]
It looks like that I can call `HSBeacon.logout()` to have `prefill()` be called again (I never called `login`…) 

Calling `HSBeacon.reset()` has no effect (despite not using secure mode…) and doesn't clear any fields, despite what the document says:
```
/**
 Resets the contact form by clearing all of its fields, custom fields and attachments. If your Beacon is in Normal Mode, calling reset will clear all contact form fields, including name and email address.

 If your Beacon is in Secure Mode, calling reset will not clear the customer’s name or email address. Those inputs will remain hidden.
 */
+ (void)reset;
```

**Comment by shaunmcilroy** [comment]
Hey @bvirlet, for the current implementation we won't call prefill every time, but will be sure to call it if you call [HSBeacon reset].

The reason we aren't guaranteeing prefill every time HSBeacon.open() is called as we've decided that it would not be correct to call prefill when a user already has a draft message in progress.

In that case it's not clear which data should take precedence so we just default to leaving a draft message intact. However when calling [HSBeacon reset] draft messages are cleared and you would therefore receive a prefill call on your next presentation of Beacon. This may be a scenario you wish to investigate. Internally, we're [tracking a card](https://helpscout.atlassian.net/browse/IOSSDK-134.) to improve the documentation around `prefill` since it has let us down a bit here, we'll update that and let you know when the change is live.

We also recommend updating to SDK version v1.0.5 to ensure you're using the latest release. The benefit here is that issues which present in the current version you're using may be addressed in a subsequent release. 

Let us know if you have any questions on the above!
