### ISSUE TITLE
Add support for the 2.1 version of Beacon (Web UI/Modes/etc.)

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#67]
Hello HelpScout support,

We have integrated the Beacon SDK Android and iOS for our project. We can see that the UI on your website and when we integrate your android SDK looks good. But the UI from when we integrate your iOS SDK is very different. Please have a look the screenshot.

Could you please let us know if it is intended?
Is it possible to get the same appearance as the Android SDK on iOS (color +
“ANSWERS”/“ASK” buttons + each article in a small card with title and first
words )?

Beacon SDK iOS versions we tried: 1.0.5, 2.0 beta

* Beacon install method: CocoaPods

**Screenshots or GIFs**
![beaconSDK_UI](https://user-images.githubusercontent.com/45462932/84106568-bf780280-aa45-11ea-89d2-1b22017fe391.png)

Thanks,
Binh

**Comment by shaunmcilroy** [comment]
Hi @BinhTNT we're currently working on implementing the same visual look for Beacon on the web but we don't have an ETA on when that'll be released just yet. Android SDK for Beacon is a little further along in development which is why you're seeing the updated look there. 

I've registered your interest for this on the internal card linked below, and we'll keep you in the loop as we progress towards a release: https://helpscout.atlassian.net/browse/IOSSDK-188

**Comment by BinhTNT** [comment]
Hi @shaunmcilroy Thank you for your information. Let's wait for new release!

**Comment by BinhTNT** [comment]
Hi @shaunmcilroy 
I come back again for the UI on iOS. As you can see the previous screenshot, the navigation bar color is black. It shows the correct theme color in HelpScout, except for after I open the Contact form by "Get in touch", then re-open the Beacon home screen, it's turned into black. Could you please let me know if it is a known issue and will be enhance in the next release for iOS ? Is it possible to have a quick fix for it when we stick to the current SDK version?

Thanks,
Binh

**Comment by shaunmcilroy** [comment]
Hi @BinhTNT this should be no longer an issue with the latest version of the beta. This occurs when the following occurs:

- If you open the Contact menu, the modal is the correct color: https://c.hlp.sc/yAu2Lkx0
- If you then dismiss it and re-open Beacon, the header is Black: https://c.hlp.sc/rRu9LNPv

Can you confirm this is no longer the case on the 2.0.0 Beta 2 release?

**Comment by BinhTNT** [comment]
Hi @shaunmcilroy Actually, I tried the version 2.0 beta without CocoaPods, but it get crashed when opening the Beacon. Currently, I prefer to install Beacon SDK via CocoaPods, and I got the build error as image related to PusherSwift framework. I have imported the Beacon from my own 3rd library. 
Here is list of framework dependencies:
  - PusherSwift (7.2.0):
  - CryptoSwift (~> 0.9)
  - ReachabilitySwift (= 4.3.0)
  - Starscream (~> 3.0.5)
  - ReachabilitySwift (4.3.0)
  - Starscream (3.0.6)

Maybe I'm missing the settings in somewhere. Can you please help me to solve it?
Thanks,
Binh
<img width="1280" alt="Screen Shot 2020-06-15 at 12 21 03 PM" src="https://user-images.githubusercontent.com/45462932/84621030-baaec500-af03-11ea-88f4-e54d25216055.png">

**Comment by ScottPetit** [comment]
Hey 👋 @BinhTNT,

If you're still having issues with the `PusherSwift` module not being found the top two answers [here](https://stackoverflow.com/questions/31065447/no-such-module-when-i-use-cocoapods) may be able to help you.  If you're not able to select the Pods scheme (because it's not in the list) you may need to close Xcode and make sure that you're opening the `.xcworkspace` that Cocoapods generated for you and not the `.xcodeproj`.

**Comment by BinhTNT** [comment]
Hi @ScottPetit 
Thanks for your instruction. I tried the solution but did not help. I also tried to import Beacon from the AppDelegate instead of my own 3rd library, it compiled successfully, but the app gets crashed due to the PusherSwift.framework again (please take a look the screenshot). I could not find PusherSwift.framework in my project so that I can embed it into.

I am really stuck in using the SDK 2.0 beta. Hope you can help me.

Thanks,
Binh

<img width="564" alt="Screen Shot 2020-06-16 at 12 53 03 AM" src="https://user-images.githubusercontent.com/45462932/84690858-5e808b00-af6d-11ea-8eb7-3c5906408bfe.png">

**Comment by ScottPetit** [comment]
Hey @BinhTNT, so just to make sure I'm clear.  Originally you tried having the Beacon pod be a dependency of your own 3rd library, right?  Could you share that podspec?  

Is the project you're trying to include this in using Swift?  If so what version of Swift?

Is there a specific reason you're not using more recent versions of Xcode?

Also just to confirm that you do see the `Pods` project in your workspace, but within that projects Pods directory you don't see PusherSwift as one of the directories?

<img width="427" alt="Screen Shot 2020-06-17 at 11 21 29 AM" src="https://user-images.githubusercontent.com/2100009/84923392-c4176900-b08c-11ea-868f-8520c41da56a.png">

**Comment by BinhTNT** [comment]
Hi @ScottPetit 
Thank you for your response!

For clarification, actually, our project is using React Native, because as we know, HS Beacon have not supported for React Native yet, so we have tried to build the bridge library in native side that is used by Javascript side. The bridge library is gonna to import Beacon from there and defines wrapper functions for Beacon API. It's a requirement when using SDK from native in React Native project. It works fine when I used SDK version 1.0.5.
<img width="1246" alt="Screen Shot 2020-06-18 at 4 08 28 PM" src="https://user-images.githubusercontent.com/45462932/85003779-df63a080-b180-11ea-8ee7-77791a20a100.png">
<img width="957" alt="Screen Shot 2020-06-18 at 3 49 57 PM" src="https://user-images.githubusercontent.com/45462932/85003856-fdc99c00-b180-11ea-8588-e79d5159f9e4.png">



Is the project you're trying to include this in using Swift? If so what version of Swift?
> No, I have tried to include Beacon into Objective-C (as you can see in the screenshots).

Is there a specific reason you're not using more recent versions of Xcode?
> Actually yes, we have crash issue on distribution build caused by a 3rd library. It happens with Xcode 11.2 or higher, so currently, we are still using Xcode 11.1 to avoid the crash. I also tried Xcode 11.2.1 and met the same issue.

Also just to confirm that you do see the `Pods` project in your workspace, but within that projects Pods directory you don't see PusherSwift as one of the directories?
> There is no problem with Pods project and dependencies directory.

Looking forward for your help!
Thanks,
Binh

**Comment by ScottPetit** [comment]
Hey @BinhTNT, thanks for all the context.  Could you let me know what's shown for the `HelpscoutBeacon` target under `General` > `Frameworks, Libraries, and Embedded Content`?

<img width="805" alt="Screen Shot 2020-06-18 at 7 27 58 AM" src="https://user-images.githubusercontent.com/2100009/85022511-06967f80-b139-11ea-9af5-2f39b9beccf9.png">

**Comment by BinhTNT** [comment]
Hi @ScottPetit 
The HelpscoutBeacon is static library.
I hope I sent correctly what you want to see.

<img width="1270" alt="Screen Shot 2020-06-18 at 8 56 40 PM" src="https://user-images.githubusercontent.com/45462932/85029951-13ea5300-b1a7-11ea-8c7a-06c4863eea48.png">

**Comment by NappyPirate** [comment]
I am also experiencing this same issue at run time when trying to use the `2.0.0-beta.2` ios helpscout sdk in a React Native (Objective C) project:
```
dyld: Library not loaded: @rpath/PusherSwift.framework/PusherSwift
  Referenced from: /Users/brandon/Library/Developer/CoreSimulator/Devices/051EC279-3A60-4C6F-AAEE-7558219745CD/data/Containers/Bundle/Application/495EE5E3-C9C8-4652-B5E5-C0AAA0ED17DB/BeaconRnTest.app/Frameworks/Beacon.framework/Beacon
  Reason: image not found
```

Here is an example project that re-creates the issue:
https://github.com/NappyPirate/BeaconRnTest

**Comment by ScottPetit** [comment]
@BinhTNT @NappyPirate,

First off Brandon thanks so much for the sample project.  It truly makes digging into this much easier.  So on one hand I have some good news in that I can now get the project to build.  On the other hand it may affect some of your other dependencies.

So Beacon 2.0.0 now includes Swift.  Cocoapods handles Swift frameworks a bit differently than Objective-C and in order to use them requires you specify `use_frameworks!` in your target definition.  @NappyPirate for your sample project this would look like this

```ruby
target 'BeaconRnTest' do
  use_frameworks!

  # all the pods that you'd like to include
end
```

The downside to this is it seems like some of the existing frameworks may not play nicely with this, notably `Flipper`, per this comment [here](https://github.com/NappyPirate/BeaconRnTest/blob/b59012249965866637dd64d2ba5fa10a005a6947/ios/Podfile#L91).  That said by commenting out those two lines and removing `Flipper` from Cocoapods I was able to successfully build and run the sample project using `use_frameworks!`.

Let me know if either of y'all have trouble with this and I'd be happy to open a PR with my working app on the sample project you provided.  Thanks again @NappyPirate.

**Comment by BinhTNT** [comment]
Hi @ScottPetit 
I tried to uncomment use_frameworks! and re-install Pods project, but it did not help. The error was the same.
I have a question, that is in the case I want to use Beacon SDK manually by downloading it without using CocoaPods, which dependencies will I need and where can I find them? Have you tried to attempt to use the SDK version 2.0.0 beta by this way?

Thanks,
Binh

<img width="1259" alt="Screen Shot 2020-06-19 at 3 51 54 PM" src="https://user-images.githubusercontent.com/45462932/85116397-7561fe80-b247-11ea-9ec8-859cf9f74682.png">

**Comment by ScottPetit** [comment]
Hey @BinhTNT, I just want to make sure that Xcode isn't have some caching problems causing that problem to persist.  Some things to try (that you may have already done):

1. Delete the .xcworkspace generated by Cocaopods and rebuild it
2. Delete Derived Data
3. Clean the Project in Xcode

Here's a [fork](https://github.com/ScottPetit/BeaconRnTest) of @NappyPirate's RN project that launches Beacon correctly, that you may want to try out as well.

As far as integrating Beacon SDK manually, we haven't yet written up documentation that reflects what's needed for Beacon 2.0.0 since it is still in Beta.  That said the [manual instructions](https://github.com/helpscout/beacon-ios-sdk#manually) should still apply +  it's dependencies which are [HSAttachmentPicker ](https://github.com/helpscout/HSAttachmentPicker) and [PusherSwift](https://github.com/pusher/pusher-websocket-swift).  PusherSwift itself has dependencies which you'll have to manage as well, which includes   [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift), [ReachabilitySwift](https://github.com/ashleymills/Reachability.swift) and [Starscream](https://github.com/daltoniam/Starscream).

Even though I know the Cocoapods integration has surely been frustrating, I would probably start with the [sample project](https://github.com/ScottPetit/BeaconRnTest) I linked to earlier.

**Comment by NappyPirate** [comment]
@ScottPetit I was under the impression, per cocoapods release notes [here](http://blog.cocoapods.org/CocoaPods-1.5.0), that since cocoapods 1.5.0 and xcode 9, you no longer need to `use_frameworks!` with swift libraries.  While removing Flipper (a debugging utility) in a simple sample project like this is trivial, enabling `use_frameworks!` in our production app breaks some of our other critical dependencies.  Could this be an issue with how the Beacon pod is distributed? or how the `vendored_libraries` is compiled?

**Comment by shaunmcilroy** [comment]
Hey @NappyPirate - just following up as per my email. I'm going to touch base with Scott and the SDK authoring team today to get you a response.

**Comment by ScottPetit** [comment]
Hey @NappyPirate so it seems like our shipping a dynamic framework is more of a historical artifact and less of a technical limitation.  

As such, we're planning on shipping at least the release version of the Beacon 2.0.0 SDK as a static framework.  There are some internal hurdles we'll have to overcome but there shouldn't be any changes when that happens on your end, aside from getting to remove the `use_frameworks!` flag from your podfile 😄 .

**Comment by ScottPetit** [comment]
We're tracking the conversion to Beacon as a static library internally [here](https://helpscout.atlassian.net/browse/IOSSDK-210).

**Comment by shaunmcilroy** [comment]
Hi @NappyPirate @BinhTNT - I've created a new Issue for the request to have Beacon distributed as a static framework and we're tracking that here: https://github.com/helpscout/beacon-ios-sdk/issues/77

Can you please open fresh issues for any other questions or feedback regarding Beacon if unrelated to the visual appearance/UI of Beacon? Thanks so much!

**Comment by BinhTNT** [comment]
Hi @shaunmcilroy Well noted! Thank you.

**Comment by NappyPirate** [comment]
I know this github issue got a little side tracked, but just checking in to confirm that the original intention of this issue was to report the inconsistency in the UI experience of the beacon on iOS compared to web.  I also wanted the confirm that part of the work to align these UI's includes making sure the iOS beacon UI honors the beacon mode (self service, neutral, ask first).

**Comment by shaunmcilroy** [comment]
Hi @NappyPirate I just replied to the last email regarding the SDK but will note here to keep all parties in the loop. This issue does relate to the visual look of Beacon and the associated features around the web/Android version currently unavailable on iOS.

The 2.1 update (in development) will bring the same features to the iOS SDK that are currently available on Beacon for Web and Beacon for Android. That includes a fresh new look, UX and modes for your team to enforce specific flows before a customer can make use of contact options.

As a rule we don't offer timelines in terms of releases as dates can slip but this issue will be updated with information as and when new releases become available, as well as via email where we'd previously noted your interest in these features.

**Comment by ScottPetit** [comment]
Hey 👋 @BinhTNT  & @NappyPirate,

Just wanted to reach out and let you know that the latest version of Beacon (2.1.0) adds support for the 2.1 UI that you see on Beacon Web and Android.  That also means `focusMode` on your Beacon config is now respected and overridable.  If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

_Since I believe both of y'all are integrating Beacon into a ReactNative I used the sample app @NappyPirate provided previously and was able to integrate Beacon 2.1.0 in it, but let us know if you run into any issues._

**Comment by ScottPetit** [comment]
Hi @BinhTNT We discovered an issue with version 2.1.0 where under certain configurations Beacon wouldn't be able to be dismissed. Therefore we decided to remove 2.1.0 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by ScottPetit** [comment]
Hey 👋 @BinhTNT & @NappyPirate,

Just wanted to reach out and let you know that the latest version of Beacon (2.1.1) adds support for the 2.1 UI that you see on Beacon Web and Android. That also means focusMode on your Beacon config is now respected and overridable. If you'd like to see what else is in this release take a look at the Changelog.

Since I believe both of y'all are integrating Beacon into a ReactNative I used the sample app @NappyPirate provided previously and was able to integrate Beacon 2.1.1 in it, but let us know if you run into any issues.
