### ISSUE TITLE
[usability] In Email form, keyboard should allow user to go to next fields

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#69]
This is a minor issue, it can be reproduced as follow in our app:

>    Launch Genius Scan iOS App
>    Tap on Settings
>    Tap on Help
>    Tap on "What can we help you with?"
>    Tap on Ask tab
>    Fill name on Name field
>    Tap on the Return button on the keyboard

# Actual behavior
Nothing happens

# Expected behavior

That button should be "Next", and it should move to the next field.

**Comment by shaunmcilroy** [comment]
Hi @bvirlet - when using your Beacon via your app I'm able to make use of the tab arrows [noted here](https://c.hlp.sc/z8u8xnJq). This is the same behaviour seen in our Beacon for Web embed.

Video showing what happens when tapping those arrows: https://c.hlp.sc/ApuAjOn6

As Custom Fields can also be included, having that button default to _Next_ would break functionality particularly if the custom field is a multiline option. 

Looking at other contact forms (e.g. Gravity Forms) the behaviour isn't consistent when viewed on an iOS device, and the return key acts as a Go key in some instances. With the entry field navigation arrows providing support already will that help solve the issue for you?

**Comment by bvirlet** [comment]
Hi @shaunmcilroy,

This issue is not critical for me but is I think good HIG feedback. I think the behavior of the Return key is to be "Next" when it makes sense to move to the next field, and to be Go or Done or Send on the last field. See: https://developer.apple.com/documentation/uikit/uireturnkeytype.

What surprised the tester was mainly that the "Return" did nothing.

**Comment by bvirlet** [comment]
Feel free to close if you don't deem this worth fixing.

**Comment by codenameDuchess** [comment]
Hi @bvirlet - thanks for raising this. We were able to duplicate the behavior you mentioned. We'll let you know if an enhancement makes it into an upcoming release.

**Comment by codenameDuchess** [comment]
Internal ticket tracking link [IOSSDK-199](https://helpscout.atlassian.net/browse/IOSSDK-199).

**Comment by ScottPetit** [comment]
Hey @bvirlet I just wanted to reach out to let you know that as of version 2.0.0 we now customize the return key and it's behavior when composing a message.

Thanks for bringing this to our attention.

**Comment by bvirlet** [comment]
Thanks @ScottPetit
