### ISSUE TITLE
Close button not visible on iOS 12 if Bold Text is selected in Accessibilty settings

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#72]
A customer of mine wasn't able to close the beacon without restarting the app. After some troubleshooting I found out that this was due to the setting "Bold Text" in accessiblity. When this is enabled on iPhone 5s/iOS 12, the close button doesn't show. 

Beacon Version: 1.0.5
Devices: iPhone 5s and iPhone 6
OS version: iOS 12.4

Steps to reproduce:
1: Open settings app
2: Open general
3: Open accessiblity
4: Enable bold text
5: Start the beacon

Actual:
The close button (x) is not visible to the user, which leaves the user no other choice than to restart the app to exit. 

Expected: 
A close button should be visible even if bold text is enabled. 

This only seem to happen on iOS 12 devices. I tried it on iOS 13 and it seems to work without problems.

**Comment by codenameDuchess** [comment]
Hi @sipersso, sorry for the trouble and thank you for the detailed steps to reproduce this issue. We'll get a fix in and reach back out once we have it in a release.

**Comment by codenameDuchess** [comment]
Internal tracking ticket https://helpscout.atlassian.net/browse/IOSSDK-202

**Comment by adrianne-helpscout** [comment]
👋 Hi @sipersso 

We investigated this issue further and it seems like it is the fault of an [iOS bug](https://developer.apple.com/forums/thread/89337) in versions 11 and 12, it was fixed in iOS 13. You can find some more discussion of this issue [here](https://stackoverflow.com/questions/53984861/bar-button-item-tint-colors-with-ios-bold-text-settings). 

One possible workaround for you would be to not set the beacon to be the same as the default iOS color. If you do this, the tint color will still be incorrect, but  it will not appear to the end user to be invisible.

**Comment by sipersso** [comment]
Thanks for the reply and for looking into this. Yes, currently the beacon color is the same as my tint color in the app. It does look like I can customize the beacon colors from the iOS app through beacon settings. This is definitely good enough.
