### ISSUE TITLE
Merged messages fails to load on iOS devices

### ISSUE THREAD

**Issue by mehedihasan619** [helpscout/beacon-ios-sdk#89]
Hi, 
I sent two messages using two separate threads from the app and merged on the web and noticed that merged conversations can no longer be accessed on the user's end. 

**Actual Outcome:** Beacon throws an error message "**There was a problem retrieving this message. Please double-check your Internet Connection and try again**" and fails to load merged conversations on the iOS device. I assure you that my internet is working fine with no issues at all.

**Expected Outcome:** Merged conversation should be automatically merged on the user's end and successfully loaded when accessing from Previous Conversations.

**Steps to replicate:**
1. Visit Help Center
2. Tap on "Get in touch"
3. Fill out the form and send the message
4. Go back to Help Center
5. Repeat step 2 and 3
6. Merge the two messages from the web
7. Now try to access the messages from Previous Conversations

Screenshot of the error: https://prnt.sc/u4cmg8

Note: This issue is also reproducible on **Android SDK**.

**Comment by shaunmcilroy** [comment]
Hi @mehedihasan619 this seems like an issue we're tracking that's unrelated to the Beacon SDK (it's the same behaviour if you try to access via Beacon from the web). Can you share with us the two conversation IDs you're merging together within your account along with the company name so we can confirm this?

Thanks.

**Comment by mehedihasan619** [comment]
Hi @shaunmcilroy,
Here is the ID 1261826044/612
Company Name: Perifit

**Comment by shaunmcilroy** [comment]
Hi @mehedihasan619 thanks for confirming those details. I've checked with our team and we can confirm this is an issue that exists with Beacon separate from the SDK which we're currently tracking: SDS-6119. 

For background, this happens if two of your customer's conversations created via Beacon have been merged in your Help Scout mailbox, and that is our culprit here. We do have this documented for our engineers, and in the short term the good news is that because Beacon messages are automatically sent to the customer's email inbox as well, so they should be able to access them there in the meantime.

To prevent it from happening, one option is to not merge conversations that have a Beacon-initiated conversation in them. That should ensure the customer is able to see them all through their Beacon. As this is unrelated to the SDK I'll close out this issue and add a tracking card in our email queue. Should that change we'll touch base with you directly via email.

**Comment by mehedihasan619** [comment]
Thank you @shaunmcilroy 
We are not merging conversations this time around. Just to have an idea, when can we expect to get this fixed/implemented?

**Comment by shaunmcilroy** [comment]
Hey @mehedihasan619 

For the convo ID 1261826044 there are two different Beacon conversations merged together ([ref](https://c.hlp.sc/rRu7Wg68)) which is the use case we described above. If you're seeing issues in other non-merged conversations please email us the details via the in-app Beacon and we'd be happy to take a look. 

We don't have a timeline on when to expect any changes to the reported issue. Our support team doesn't determine our future product roadmap and so can't make any promises in terms of when we will take something on as a company, but I have added your plus one to our internal tracking tool for this request. 

We use that tool to manage follow-up with customers, so if we have any news to share you'll be on the list to receive an update.

**Comment by mehedihasan619** [comment]
Gotcha! Thank you once again @shaunmcilroy,
As far as we have noticed the issue is reproducible only when two conversations are merged.
